shell zsh
# -----------------------------------------------------------------------------
# Window Layout & Padding
# -----------------------------------------------------------------------------
window_padding_width        15
placement_strategy          center
hide_window_decorations     yes

# -----------------------------------------------------------------------------
# Tokyo Night Color Scheme
# -----------------------------------------------------------------------------
background                  #1a1b26
background_blur		    30
background_opacity          .65
foreground                  #a9b1d6
selection_background        #343b58
selection_foreground        #a9b1d6
url_color                   #73daca
cursor                      #c0caf5

# Tabs
active_tab_background       #7aa2f7
active_tab_foreground       #1f2335
inactive_tab_background     #353a52
inactive_tab_foreground     #545c7e

# Windows
active_border_color         #7aa2f7
inactive_border_color       #292e42

# Terminal Colors (Ansi 16)
color0                      #414868
color8                      #414868
color1                      #f7768e
color9                      #f7768e
color2                      #9ece6a
color10                     #9ece6a
color3                      #e0af68
color11                     #e0af68
color4                      #7aa2f7
color12                     #7aa2f7
color5                      #bb9af7
color13                     #bb9af7
color6                      #73daca
color14                     #73daca
color7                      #c0caf5
color15                     #c0caf5
